[package]
name = "rustBasics"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "enums_and_pattern_matching"
path = "week1/enumsAndPatternMatching.rs"

[[bin]]
name = "structs_in_rust"
path = "week1/structsInRust.rs"

[[bin]]
name = "basics_of_rust"
path = "week1/basicsOfRust.rs"

[[bin]]
name = "guess_the_number"
path = "week1/guessTheNumber.rs"

[dependencies]
rand = "0.5.5"
colored = "2.0.0"
